language: ruby
rvm:
- 2.0.0
install: bundle install
script: bundle exec rake build
after_success:
- bundle exec rake s3
- bundle exec rake purge
notifications:
  email:
    recipients:
    - me@tammersaleh.com
env:
  global:
  - secure: wRRtfLr+xMLK8+T8hz4zlfW6wNYGiUDM/dh6zZkwAQCIJ1Cfs6Frf9cRwCNZgUNWIBxAgLUQkyx+hLa1vBq2+C7qt7TVjsIWwKxlkg5bNFmp+kMji8PBhX11a8YvHdAduixqhCN5Pop8PxVFNja8ne7ZDmnEM2+/YO6wwRXaYH0=
  - secure: EQhSokIkvfLzJqgm66+G5GSozj7dwhHkxhpjCQc3G6zth2oPOp2rlzk+KrWw8P2gjppSXAK9wODiv1DeEAysyfQDVfSrddfckVzD+tOX/6fcK0AJBCRPxNZpYPC5iio1Czehf3ALUdVYOaOu+S7wuUOjakEQNuZyujaF2yitSSI=
  - secure: edF9pU+RTmpfK5qjNvU4trgSiyT0tB0WTZvRoAFUwgIZAJ9Uktp+TPP+IaOr7wiLEAyuTPVEiA3Jt6yOFmjfjz2ExJjXNQGr12H1WvfhTqjfJMVN+s5m5uMvk3Cv4HWLitpPLqJWH5b1LHqDK+OwWPaPsMFEG6gGS1+PG7y/m00=
